### ISSUE TITLE
"Edit this page on GitHub" links result in a HTTP 404

### ISSUE THREAD

**Issue by bebold-jhr** [awsdocs/aws-security-hub-user-guide#16]
The **Edit this page on GitHub** links of this documentation result in a HTTP 404:

Example:
Documentation page: https://docs.aws.amazon.com/securityhub/latest/userguide/asff-compliance.html
Link for "Edit this page on GitHub": https://github.com/awsdocs/aws-security-hub-user-guide/tree/master/doc_source/asff-compliance.md

**Comment by prakaprjAWS** [comment]
There was an issue with that markdown file, which I just fixed @bebold-jhr . Please try it again. Thanks.

**Comment by bebold-jhr** [comment]
Links are in place again. Thank you.
