### ISSUE TITLE
Contradicting passages on option to enable Security Hub for all accounts?

### ISSUE THREAD

**Issue by bebold-jhr** [awsdocs/aws-security-hub-user-guide#18]
To me there seems to be a contradiction in the documentation regarding the option to enable Security Hub automatically for all organization accounts.

On [this page](https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-accounts-orgs.html) it says 

> If the Security Hub administrator account has not enabled the option to automatically enable new organization accounts, then  the Accounts page displays a message at the top of the page. The message contains an Enable option.
>
> When you choose Enable, Security Hub performs the following actions:
>
> * **Enables all of the current organization accounts as member accounts.**
> * [...]

But on [this page](https://docs.aws.amazon.com/securityhub/latest/userguide/accounts-orgs-auto-enable.html) is says

> When you enable the automatic enablement setting, Security Hub begins to enable new accounts as member accounts when they are added to the organization. **It does not enable existing organization accounts that are not enabled as member accounts.** Security Hub also cannot automatically enable accounts that already belong to another administrator account.

My understanding of the first extract is that if I enable the option to automatically enable Security Hub for all accounts of my organization it will enable Security Hub for all existing accounts and make them a member. (Status: "Enabled")

From the second extract I understand that if I enable that option it will not have an effect on the member status of already existing accounts (Status: "Not a member"). Instead it will enable Security Hub on all accounts created from then on and make them a member.

From experience I'd say that the latter is correct.
Is my understanding of the text wrong or is the documentation confusing here?

**Comment by prakaprjAWS** [comment]
Thank you for telling us about this issue @bebold-jhr. I am looking into this and will leave notes about my progress here.

**Comment by prakaprjAWS** [comment]
I have updated this part of the docs so they are clearer. Thanks for your contribution.
