### ISSUE TITLE
Remediation instructions are missing for rule Autoscaling.6

### ISSUE THREAD

**Issue by schwichti** [awsdocs/aws-security-hub-user-guide#26]
The remediation instructions were copied and pasted from another rule. Therefore the actual remediation instructions are missing. Please provide the right remediation instructions.

https://github.com/awsdocs/aws-security-hub-user-guide/blob/master/doc_source/securityhub-standards-fsbp-controls.md#autoscaling6-auto-scaling-groups-should-use-multiple-instance-types-in-multiple-availability-zones

**Comment by prakaprjAWS** [comment]
Thank you for your comment @schwichti. I have corrected this problem and provided the remediation instructions for AutoScaling.6 in the documentation.
