### ISSUE TITLE
Why do some ARNs have account IDs and others don't?

### ISSUE THREAD

**Issue by AndrewCharlesHay** [awsdocs/aws-security-hub-user-guide#27]
For example the ARN for [Aqua Security](https://github.com/awsdocs/aws-security-hub-user-guide/blob/master/doc_source/securityhub-partner-providers.md?plain=1#L51) has no account ID set but [Armor](https://github.com/awsdocs/aws-security-hub-user-guide/blob/master/doc_source/securityhub-partner-providers.md?plain=1#L75) has an account ID hardcoded into the ARN. An explanation for this pattern would be appreciated 😀 

Related PR: https://github.com/aquasecurity/trivy/pull/2852

**Comment by prakaprjAWS** [comment]
Thank you for your question @AndrewCharlesHay. Only third party integrations that send findings to Security Hub should have an ARN. I have corrected this in the documentation now.

**Comment by AndrewCharlesHay** [comment]
Thank you @prakaprjAWS ! Say hi to Andy Jassy for me 😃
