### ISSUE TITLE
AWS Chatbot 

### ISSUE THREAD

**Issue by danieloldberg** [awsdocs/aws-security-hub-user-guide#28]
https://github.com/awsdocs/aws-security-hub-user-guide/blob/master/doc_source/securityhub-internal-providers.md
In Overview of AWS service integrations with Security Hub table, AWS Chatbot is marked "Sends findings" but in text it says "Receives findings" / "AWS Chatbot receives findings from Security Hub.".
Assume the latter is the correct one.

**Comment by prakaprjAWS** [comment]
@danieloldberg The table is correct now. Thanks for your feedback!
