### ISSUE TITLE
IAM Policy: Scope down Security Hub IAM policy to Specific Actions  

### ISSUE THREAD

**Issue by ajarawat1992** [awsdocs/aws-security-hub-user-guide#5]
Currently Security Hub IAM Policy has securityhub:* that include all the actions. As well as, ServiceLinkedRole Sid has * in the resource section.

**Comment by ajarawat1992** [comment]
Current IAM policy:

{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": "securityhub:*",
            "Resource": "*"    
        },
        {
            "Effect": "Allow",
            "Action": "iam:CreateServiceLinkedRole",
            "Resource": "*",
            "Condition": {
                "StringLike": {
                    "iam:AWSServiceName": "securityhub.amazonaws.com"
                }
            }
        }
    ]
}

**Comment by jmanwiller** [comment]
This is a service issue rather than a doc issue - the doc reflects the service. I will verify with the service team that the doc accurately reflects the current service config, and pass this feedback along.

**Comment by jmanwiller** [comment]
I have passed along the feedback to the service team.

The policy is structured this way intentionally to support customer use across regions. It is a common structure across services.

If you would like to raise the issue with the service team, you can work through support or create a feedback issue from within the Security Hub console.

**Comment by ajarawat1992** [comment]
Thank you for your response. I will raise the issue with the service team.

**Comment by jmanwiller** [comment]
The issue you created was a documentation feedback issue, not a service issue, but I reassigned it to a service team CTI.
