### ISSUE TITLE
CIS AWS Foundations Benchmark v1.3.0

### ISSUE THREAD

**Issue by bwhaley** [awsdocs/aws-security-hub-user-guide#8]
This probably isn't the right place to open this issue, so please point me to a better place if you know of one. 

Any plans to support the [updated 1.3.0 version](https://www.cisecurity.org/benchmark/amazon_web_services/) of the Benchmark? This was release in August 2020 I believe.

**Comment by jmanwiller** [comment]
I have passed along your question to the service team, and will let you know when I get a response.

Another avenue might be Support - they can also pass along questions to the service team.

**Comment by bwhaley** [comment]
Thanks so much! I'll be awaiting the response with bated breath. :)

**Comment by jmanwiller** [comment]
So according to the product manager, it is on the near-term roadmap. Don't have any more detail than that.

**Comment by bwhaley** [comment]
Alright. Thanks for the prompt response!
